spring:
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
  jms:
    template:
      default-destination: email-notification

email:
  from: no-reply@example.com
  subject: Уведомление о новом контракте

rabbit:
  username: guest
  password: guest
  email-notification-queue: email-notification